### ISSUE TITLE
デフォルトでdevelopブランチにPRが作成されるように設定する

### ISSUE THREAD

**Issue by gkumi5638** [gkumi5638/imasora#17]

**Comment by masatakashida** [comment]
https://qiita.com/no-use-kuro/items/0d9a5b2d113902495fac

**Comment by gkumi5638** [comment]
設定しました！
[参考記事](https://qiita.com/unsoluble_sugar/items/0603187d5a732f91d502)

**Comment by gkumi5638** [comment]
記事ありがとうございます！
