### ISSUE TITLE
使用技術の選定

### ISSUE THREAD

**Issue by masatakashida** [gkumi5638/imasora#2]
## なぜやるか
imasoraを作成するにあたり、どの技術で作成するか決定したいため

## 候補
- Ruby On Rails(Ruby)
- Flask(Python)
- Django(Python)
- Laravel(PHP)

**Comment by masatakashida** [comment]
画像処理系やるなら，pythonがよさそうかなと思いました！
OpenCVというライブラリが使用できます！

**Comment by masatakashida** [comment]
@gkumi5638 さんが一番できるのはRailsですかね？
できるものでサクッと作るのもありかと思います。

あとは、職場で使用するPHPとかも

ベストなものを選んでみてください！

**Comment by gkumi5638** [comment]
ありがとうございます！
pythonで作ってみたいです。
理由は、画像処理もありますし、違う技術に触れてみたいからです。
比較することで学びが深まると良いと思いました。

**Comment by masatakashida** [comment]
READMEに記載してよろしくです!
