### ISSUE TITLE
ブランチ運用について

### ISSUE THREAD

**Issue by masatakashida** [gkumi5638/imasora#9]
@gkumi5638 
今後，masterブランチは本番サーバ用とかになっていくと思いますが，どんなブランチ運用を想定していますか？

**Comment by gkumi5638** [comment]
@masatakashida 
直接masterにあげていました。
今後は、git-flowで考えています。

**Comment by masatakashida** [comment]
@gkumi5638 
了解です！
Developブランチはテストサーバとかあげたいですね！

**Comment by masatakashida** [comment]
## ToDO
- [ ] ブランチ運用をREADMEに記載する．

**Comment by gkumi5638** [comment]
@masatakashida 
こちらよろしければ、お願いしてもよろしいでしょうか！？

**Comment by gkumi5638** [comment]
@masatakashida 
git flowについて、質問があります。
現在は、masterにマージしていますが、developブランチを作成し、そこにマージしていくという流れで認識は合っていますでしょうか？
実際にしたことがない為、確認したいです。

[git flowについて確認した記事](https://qiita.com/mint__/items/bfc58589b5b1e0a1856a)

**Comment by masatakashida** [comment]
@gkumi5638 
それで良いと思います！

**Comment by gkumi5638** [comment]
@masatakashida 
了解しました！
ありがとうございます！
